---
name: Bash CI

on:
  push:
    branches: [ master ]

jobs:
  lint-and-formatter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt update && sudo apt install shellcheck shfmt --yes

      - name: Run formatter using shfmt
        run: shfmt -l -i 2 .

      - name: Run shellcheck
        run: find . -name "*.sh" -type f -exec shellcheck {} \;
