---
name: Lua CI

on:
  push:
    branches: [ master ]

jobs:
  formatter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "0.20.0"
          args: --check --config-path hammerspoon/.stylua.toml .
