name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'
    - 'tools/*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          # - 26.1
          # - 26.2
          # - 26.3
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v1
    - name: Build configuration
      run: './run-tests.sh'
